apiVersion: apps/v1
kind: Deployment
metadata:
  name: wheatherapp-deployment
spec:   
  replicas: 3
  selector:
    matchLabels:
      app: wheatherapp
  template:
    metadata:
      labels:
        app: wheatherapp
    spec:
      containers:
        - name: wheatherapp
          image: akshayb412/wheatherapp:6033
          ports:
            - containerPort: 5000
